#DAY3PROJECT#TREASURE ISLAND
#THIS IS THE TREASURE ISLAND GAME WHERE USER HAVE TO CHOOSE RIGHT TO WIN;)
game=True
while game==True:
    print("--\--------\--------\----------\----------\--------\-")
    print("------____________________________________-----\-----")
    print("--\--||\                                  \--------\-")
    print("-----||+\                                  \---\-----")
    print("--\--|| +\__________________________________\------\-")
    print("-----||+ +||+++++++++++++++88+++++++++++++++||-\-----")
    print("--\--||*+ ||               88               ||-----\-")
    print("-----||**+||++++++++++++++++++++++++++++++++||-\-----")
    print("--\--||+**||********************************||-----\-")
    print("-----|| +*||********************************||-\-----")
    print("=====||  +||++++++++++++++++++++++++++++++++||-----\-")
    print("=======\  ||                                ||=======")
    print("========\o||oooooooooooooooooooooooooooooooo||=======")
    print("=========\||________________________________||=======")
    print("WELLCOME TO THE GAME OF TREASURE ISLAND!\n to win this game u have to choose the most relevent and correct answer of the question.\nSo are you ready!")
    name= input("please enter your name: ")
    print(f"\n\nHELLO {name}!! so the plot of the game is:")
    print("\nyou went on the jungle safari with your friends and while wandering around you get lost in the forest.\nyou were shouting for help and suddenly you notic something is watching you,\nyou stilled and slowly turn to face what it is.\nand there it was among the bushes wide golden eyes watch you with hunger.\nyou recognise it, it was a WEREWOLF, now what are you gonna do? RUN OR WAIT? ")
    print("      /^\      /^\ ")
    print("      |  \    /  | ")
    print("      ||\ \../ /|| ")
    print("      )'        `( ")
    print("     ,;`w,    ,w';, ")
    print("     ;,  ) __ (  ,; ")
    print("      ;  \(\/)/  ;; ")
    print("     ;|  |vwwv|    ``-... ")
    print("      ;  `lwwl'   ;      ```''-. ")
    print("     ;| ; `""' ; ;              `. ")
    print("      ;         ,   ,          , | ")
    print("      '  ;      ;   l    .     | | ")
    print("      ;    ,  ,    |,-,._|      \; ") 
    print("       ;  ; `' ;   '    \ `\     \; ")
    print("       |  |    |  |     |   |    |; ") 
    print("       |  ;    ;  |      \   \   (; ")
    print("       | |      | l       | | \  | ")
    print("       | |      | |       | |  ) | ") 
    print("       | |      | ;       | |  | | ")
    print("       ; ,      : ,      ,_.'  | | ")
    print("      :__'      | |           ,_.' ")
    print("               `--' ")

    we=input("run(r) OR wait(w)?: ").lower()
    if we=="r":
        print("\nyou are aimlessly running with werewolf on your foot, and you reach the end of the cliff. looking down you see the river,\nwhen you look to left you found the river begins there and there is a rocky hill-lock, to your right there's a road going down to river.\nSO WHAT DO YOU CHOOSE? ")
        di=input("left(l) OR right(r)?: ").lower()
        if di=="l":
            print("\nnow that was difficult to choose, but here you are running toward the rocky hill\nand you reached the foot of hill.")
            print("       ___/\                _ ")
            print("   _  /     \      /\      / \ ")
            print("  / \/       \----/  \   _/   \  ") 
            print(" /   \          /\    \ /      \ ") 
            print("/_____\________/__\____/________\ ") 
            cl=input("are you going to wait for some one to come and save you OR are you going to climb up the hill\nwait(w) OR climb(c)?:").lower()
            if cl=="c":
                print("werewolf was not able to come up after you, and BRAVO! you just saved your life even when the climbing was hard.")
            else:
                print(f"GAME OVER! {name} you waited too long and just become the WEREWOLF LUNCH..............")
                exit()    
        if di=="r":
            print("\nnow that was difficult to choose, but here you are running toward the river\nOnce you reached the bank of river you found that theres the boat in the middle of river\nand with the current flow of water it is moving toward you\nNOW you can either wait OR get ready to swim the half of river")
            print("\n")
            print("        _                _ ")
            print("        \```-........-```/  ")
            print("~~~~~~~~~\     \        /~~~~~~~~")
            print("~~~~~~~~~~~~~~~~()~~~~~~~~~~~~~~~")
            print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
            print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
            si=input("so what is your choose, swim(s) OR wait(w)?: ").lower()
            if si=="s":
                print("\nwerewolf was not able to come up after you, and BRAVO! you just saved your life even when the swimming in river was very difficult.")
            else:
                print(f"GAME OVER! {name} you waited too long and just become the WEREWOLF LUNCH..............\n")
                exit()
        print("           ,@@@@@@@,")
        print("   ,,,.   ,@@@@@@/@@,  .oo8888o.")
        print(",&%%&%&&%,@@@@@/@@@@@@,8888\88/8o")
        print(",%&\%&&%&&%,@@@\@@@/@@@88\88888/88'")
        print("%&&%&%&/%&&%@@\@@/ /@@@88888\88888'")
        print("%&&%/ %&%%&&@@\ V /@@' `88\8 `/88'")
        print("`&%\ ` /%&'    |.|        \ '|8'")
        print("    |o|        | |         | |")
        print("    |.|        | |         | |")
        print("jgs \\/ ._\//_/__/  ,\_//__\\/.  \_//__/_")
        print("\nYou are now on the other drak side of forest free from the wild animals now and smaller in area,\nbut this side of forest is MAGICAL and full of different dark creatures, who roam freely and hunt in night")
        print("\nLooking around, it's almost evening soon you will see twilight, you need to find the edge of forest where doors will appear.\nthis magical forest have the tallest, beautifull and siren woods, they acutally seem alive watching your every move.")
        run=(input("so are you going to walk slowly in this woods OR are you going run as fast as possible.\nwalk(w) OR run(r)?: ")).lower()
        if run=="r":
            print(f"\nCLEVER CHOICE! {name}")
        else:
            print(f"GAME OVER! {name} you definitly didn't become the lunch of werewolf, but now you have become the DINNER FOR DARK CREATURES..........\n ")
            exit()
        print("\nyou have ran a long distance and now edge of forest is at the eyesight.few more step and you reach the edge.\nin front of you are 3 diffent wooden door in 3 diffent colour.\neach door have a special message on it.\nyou have to choose only one of them,\n\nONE LAST CHOICE TO DO! if you choose the worng one death will occur in one or another way, so choose CLEVERLY!")
        
        print("     _~~~~_               _~~~~_               _~~~~_")
        print("  _~~      ~~_         _~~      ~~_         _~~      ~~_")
        print("_~            ~_     _~            ~_     _~            ~_")
        print("| ____________ |     | ____________ |     | ____________ |")
        print("||RRRRRRRRRRRR||     ||WWWWWWWWWWWW||     ||BBBBBBBBBBBB||")
        print("||RRRRRRRRRRRR||     ||WWWWWWWWWWWW||     ||BBBBBBBBBBBB||")
        print("||RRRRRRRRRRRR0|     ||WWWWWWWWWWWW0|     ||BBBBBBBBBBBB0|")
        print("||RRRRRRRRRRRR||     ||WWWWWWWWWWWW||     ||BBBBBBBBBBBB||")
        print("||RRRRRRRRRRRR||     ||WWWWWWWWWWWW||     ||BBBBBBBBBBBB||")
        print("|--------------|     |--------------|     |--------------|")
        print("|______________|     |______________|     |______________|")
        door=input("1st door is RED with the message 'DEATH WAITS FOR THE ONE WHO WAIT',\n2nd door is WHITE with message 'DEATH WAITHS FOR THE ONE WHO HIDE',\n3rd door is BLACK with message 'DEATH WAITS FOR THE ONE WHO TAKES THE STEP FORWARD'.\n(tip: think logical on each message)\nSo, what's your choose red(r),white(w),black(b).").lower()
        if door=="b":
            print(f"YOU ARE INDEED VERY CLEVER {name}! you got the logic correct the doors says,'death will have to wait for the one who will bravely take the step forward in each situation.'\n")
        elif door=="r":
            print(f"GAME OVER! {name} you didn't think logical the door says,'death will come after the one who do not take action when necessary'\n")
            exit()
        else:
            print(f"GAME OVER! {name} you didn't think logical the door says,'death will definity come for the one who hide from the hard situation'\n")
            exit()
    else:
        print(f"GAME OVER! {name} you waited too long and just become the WEREWOLF LUNCH..............\n")        
    game_on=input("do you want to play again?(yes/no): ")
    if game_on=="no":
        game=False
        print("thank you for visiting.")

    